### ISSUE TITLE
Radio buttons are selected all active one instead of a single group

### ISSUE THREAD

**Issue by inglesuniversal** [videsk/aoform#2]
`

			  {
			    "type": "radio",
			    "name": "listening-p1-q1",
			    "label": "Listening Test - Part 1 Question 1",
			    "values": [
			    	{"label":"A","value":"a"},
					{"label":"B","value":"b"},
					{"label":"C","value":"c"}
			    ]
			  },

			  {
			    "type": "radio",
			    "name": "listening-p1-q2",
			    "label": "Listening Test - Part 1 Question 2",
			    "values": [
			    	{"label":"A","value":"a"},
					{"label":"B","value":"b"},
					{"label":"C","value":"c"}
			    ]
			  },

			  {
			    "type": "radio",
			    "name": "listening-p1-q3",
			    "label": "Listening Test - Part 1 Question 3",
			    "values": [
			    	{"label":"A","value":"a"},
					{"label":"B","value":"b"},
					{"label":"C","value":"c"}
			    ]
			  },

			  {
			    "type": "radio",
			    "name": "listening-p1-q4",
			    "label": "Listening Test - Part 1 Question 4",
			    "values": [
			    	{"label":"A","value":"a"},
					{"label":"B","value":"b"},
					{"label":"C","value":"c"}
			    ]
			  },

`

All the code above is taken as a single RADIO button... IF I select a different question... The focus of the radio button is change to ONLY one answer and not one per row or question.

Thanks

**Comment by matiaslopezd** [comment]
Hi @inglesuniversal this library was deprecated. Please use https://github.com/videsk/DynForms

We're working in english documentation.
